hl.on("hyprland.start", function ()
    hl.exec_cmd("QML2_IMPORT_PATH=/home/pruebas/jozet-dotfiles/backend/build quickshell")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("systemctl --user restart pipewire pipewire-pulse wireplumber")
    hl.env("XCURSOR_SIZE", "16")
    hl.env("HYPRCURSOR_THEME", "capitaine-cursors")
    hl.exec_cmd("hypridle")
end)
