hl.on("hyprland.start", function ()
    hl.exec_cmd("QML2_IMPORT_PATH=/home/pruebas/jozet-dotfiles/backend/build quickshell")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("pipewire")
    hl.exec_cmd("wireplumber")
    hl.env("XCURSOR_SIZE", "16")
    hl.env("HYPRCURSOR_THEME", "capitaine-cursors")
end)
