hl.on("hyprland.start", function ()
    hl.exec_cmd("quickshell")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("pipewire")
    hl.exec_cmd("wireplumber")
    hl.env("XCURSOR_SIZE", "16")
    hl.env("HYPRCURSOR_THEME", "capitaine-cursors")
end)
