                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
fastfetch                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                           
# Paleta personalizada para el comando ls                                                                                                                                                                                                                                                                           
eval "$(dircolors -b ~/.dircolors)"                                                                                                                                                                                                                                                                                        
eval "$(starship init zsh)"                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                           
# Opciones del Historial                                                                                                                                                                                                                                        
setopt APPEND_HISTORY      # Guarda el historial conforme se ejecutan los comandos                                                                                                                                                                                                                                         
setopt SHARE_HISTORY       # Comparte el historial entre todas las pestañas/ventanas                                                                                                                                                                                                                                       
setopt HIST_IGNORE_DUPS    # Evita duplicados seguidos                                                                                                                                                                                                                                                                     
HISTFILE=~/.zsh_history                                                                                                                                                                                                                                                                                                    
HISTSIZE=10000                                                                                                                                                                                                                                                                                                             
SAVEHIST=10000                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                           
# Personalización de colores para Zsh Syntax Highlighting (Debe ir ANTES de cargar el plugin)                                                                                                                                                                                                                              
typeset -A ZSH_HIGHLIGHT_STYLES                                                                                                                                                                                                                                                                                            
ZSH_HIGHLIGHT_STYLES[command]='fg=white,bold'                                                                                                                                                                                                                                                                              
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=magenta'                                                                                                                                                                                                                                                                          
ZSH_HIGHLIGHT_STYLES[alias]='fg=67,bold'                                                                                                                                                                                                                                                                                   
ZSH_HIGHLIGHT_STYLES[builtin]='fg=white'                                                                                                                                                                                                                                                                                   
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red,bold'                                                                                                                                                                                                                                                                          
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'                                                                                                                                                                                                                                                                                       
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=yellow'                                                                                                                                                                                                                                                                     
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=121'                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                           
# Carga de Plugins                                                                                                                                                                                                                                     
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh                                                                                                                                                                                                                                          
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                           
# Dynamic System Paths                                                                                                                                                                                                                                                                                                     
export WALLPAPER_DIR="/home/jozet/.local/share/wallpapers/"                                                                                                                                                                                                                                                                
export SCRIPT_DIR="/home/jozet_arch/.config/hypr/scripts"                                                                                                                                                                                                                                                                  